# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisAiAgent
                                 A QGIS plugin
 AI-powered spatial queries inside QGIS
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-06
        copyright            : (C) 2026 by kodeezabdullah
        email                : abdullah.gis.services@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load QgisAiAgent class from file QgisAiAgent.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_ai_agent import QgisAiAgent
    return QgisAiAgent(iface)
