name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to QGIS Plugin Repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci

      - name: Deploy plugin
        run: >-
          qgis-plugin-ci release ${{ github.ref_name }}
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --osgeo-username ${{ secrets.OSGEO_USER }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
